import os
import asyncio
import logging
import uuid
import tempfile
from datetime import datetime, timezone
from pathlib import Path
from engine.db import DatabaseManager
from engine.models import Base, Plan, Task, Message, MessageHeader, MessageType
from engine.repository import MessageRepository
from engine.workflow import process_task_message
from engine.services.sandbox import LocalPythonSandbox
from engine.services.execution import ExecutionService
from engine.orchestrator import Orchestrator
from sqlalchemy import select

# Setup logging
logging.basicConfig(
    level=logging.INFO,
    format='%(asctime)s - %(name)s - %(levelname)s - %(message)s'
)
logger = logging.getLogger("firma-test-run")

async def setup_integration_scenario(session, prompt: str):
    """
    Prepares the DB state for an E2E integration test.
    Creates a project, plan, and a task in CODING phase.
    """
    logger.info(f"Setting up scenario for: {prompt}")
    
    project_id = "P-INTEGRATION"
    from engine.models import Project
    project = Project(id=project_id, name="Integration Test Project")
    session.add(project)
    
    plan_id = f"plan-{uuid.uuid4().hex[:8]}"
    plan = Plan(id=plan_id, project_id=project_id, version=1, name=prompt[:30], status="IN_PROGRESS")
    session.add(plan)
    project.active_plan_id = plan_id
    
    task_id = "T1"
    # Criteria: multiply 2 and 3, result should be 6.0
    criteria = ["CMD:python main.py 2 3:6.0"]
    task = Task(
        id=task_id, 
        plan_id=plan_id, 
        state="READY", 
        execution_phase="CODING", 
        assigned_role="CODER",
        expected_artifacts=["main.py"],
        acceptance_criteria=criteria
    )
    session.add(task)
    await session.commit()
    
    return project_id, plan_id, task_id

async def main():
    # 1. Infrastructure
    db_file = "firma_test_run.db"
    if os.path.exists(db_file): 
        try:
            os.remove(db_file)
        except OSError:
            pass
            
    db_url = f"sqlite+aiosqlite:///{db_file}"
    db_manager = DatabaseManager(db_url)
    await db_manager.initialize_db()
    await db_manager.create_tables(Base)
    
    # Artifact store setup
    artifact_dir = tempfile.TemporaryDirectory()
    os.environ["FIRMA_ARTIFACT_STORE_DIR"] = artifact_dir.name
    
    # Services
    sandbox = LocalPythonSandbox()
    exec_service = ExecutionService(sandbox)
    
    # Mock Scheduler
    class SimpleScheduler:
        def assign_unassigned_ready_tasks(self):
            pass 
    scheduler = SimpleScheduler()
    
    # Mock Transport
    class MockTransport:
        async def poll(self): return []
        async def connect(self): pass
        async def disconnect(self): pass

    transport = MockTransport()
    
    # 2. Start Orchestrator in background
    orchestrator = Orchestrator(db_manager, scheduler, transport, exec_service, sandbox)
    orch_task = asyncio.create_task(orchestrator.run_forever())
    
    try:
        # Load the real code generated by the LLM
        with open("multiplication_main.py", "r") as f:
            real_code = f.read()
            
        prompt = "Write a Python CLI script that multiplies two numbers passed as arguments."
        
        # Step A: Setup the state
        async with db_manager.session_scope() as session:
            project_id, plan_id, task_id = await setup_integration_scenario(session, prompt)
        
        # Step B: Simulate LLM Worker sending a TASK_RESULT
        # We build a proper WorkerResponse payload that the Guardian expects
        worker_payload = {
            "message_id": str(uuid.uuid4()),
            "task_id": task_id,
            "state_revision": 0,
            "sender_role": "CODER",
            "event": "CODE_SUBMITTED",
            "timestamp": datetime.now(timezone.utc).isoformat(),
            "artifacts": {
                "files": [
                    {"path": "main.py", "action": "CREATE", "content": real_code}
                ]
            }
        }
        
        msg = Message(
            header=MessageHeader(
                message_id=worker_payload["message_id"],
                sender="llm-worker",
                recipient="engine",
                message_type=MessageType.TASK_RESULT,
                plan_id=plan_id
            ),
            payload=worker_payload
        )
        
        # Step C: Process the message through the pipeline (Guardian -> ArtifactStore -> DB)
        async with db_manager.session_scope() as session:
            success = await process_task_message(session, msg, task_id, MessageType.TASK_RESULT, project_id)
            if not success:
                logger.error("Pipeline failed to process TASK_RESULT!")
                return

        logger.info("TASK_RESULT processed. Task should now be in SUBMITTED state.")
        
        # Step D: Wait for the orchestrator's verification loop to pick it up
        logger.info("Waiting for engine to verify real LLM code via Orchestrator tick...")
        while True:
            async with db_manager.session_scope() as session:
                result = await session.execute(select(Task).filter(Task.id == task_id))
                task = result.scalars().first()
                
                if task and task.state == "VERIFIED":
                    logger.info(f"🚀 Task {task_id} has been VERIFIED by the engine using real LLM code!")
                    break
                elif task and task.state == "READY" and task.execution_phase != "CODING":
                    # If it went back to READY but changed phase, it's a fail
                    logger.error(f"❌ Task {task_id} failed verification and was reset.")
                    break
            await asyncio.sleep(0.5)
            
    finally:
        await orchestrator.stop()
        orch_task.cancel()
        artifact_dir.cleanup()

if __name__ == "__main__":
    asyncio.run(main())
